# Generated by Django 4.2.7 on 2023-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_camiseta_gender_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='initial_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='initial_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
